---
run:
  skip-files:
    - ".*_test.go"
linters:
  enable-all: true
  disable:
    # it should improve to support more known patterns
    - varnamelen
    # deprecated linters
    - varcheck
    - deadcode
    - nosnakecase
    - revive
    - ifshort
    - structcheck
    - maligned
    - scopelint
    - golint
    - interfacer
    - exhaustivestruct
    - ireturn
    - cyclop
    - wrapcheck
    - nolintlint
